version: "3"
services:
  ades:
    build:
      context: .
      dockerfile: ades.Dockerfile
    image: 52north/ades:latest
    ports:
      - 8082:8080
    environment:
      SERVICE_SERVICE_URL: https://riesgos.52north.org/javaps/service
      SERVICE_PROVIDER_INDIVIDUAL_NAME: Jane Doe
      SERVICE_PROVIDER_POSITION_NAME: First Line Supporter
      DOCKER_ENVPREFIX: TEST_
      TEST_MY_PROPERTY: custom-value
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      network:
        ipv4_address: 172.23.164.103
  
networks:
  network:
      external:
        name: main_network
    
