#/bin/bash

echo "INPUT_HAZARD=$INPUT_HAZARD"
echo "INPUT_COUNTRY=$INPUT_COUNTRY"
echo "INPUT_HEIGHT=$INPUT_HEIGHT"
echo "INPUT_VELOCITY=$INPUT_VELOCITY"
echo "OUTPUT_DAMAGE_CONSUMER_AREAS=$OUTPUT_DAMAGE_CONSUMER_AREAS"


python3 ./run_analysis.py --country $INPUT_COUNTRY --hazard $INPUT_HAZARD --intensity_file $INPUT_HEIGHT $INPUT_VELOCITY --output_file $OUTPUT_DAMAGE_CONSUMER_AREAS